version: '3.9'
x-aws-vpc: "vpc-049300cf423e2a4bc"
x-aws-cluster: project
x-aws-loadbalancer: "proje-LoadB-YZG204ECXYER"
services:
  web:
    build: .
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tundaa:latest
    command: /bin/sh -c "bundle exec rails db:migrate RAILS_ENV=production &&
             bundle exec rails s -p 80 -b '0.0.0.0'"
    ports:
      - '80:80'
    environment:
      - 'RAILS_ENV=production'
      - 'RAILS_SERVE_STATIC_FILES=true'
      - 'RAILS_LOG_TO_STDOUT=true'
      - 'RACK_ENV=production'
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - TUNDAA_DATABASE_PASSWORD=$DATABASE_PASSWORD
      - GITHUB_KEY=$GITHUB_KEY
      - GITHUB_SECRET=$GITHUB_SECRET
      - GOOGLE_KEY=$GOOGLE_KEY
      - GOOGLE_SECRET=$GOOGLE_SECRET
    secrets:
      - TUNDAA_DATABASE_PASSWORD
      - GITHUB_KEY
      - GITHUB_SECRET
      - GOOGLE_KEY
      - GOOGLE_SECRET
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        x-aws-min_percent: 50
        x-aws-max_percent: 200
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=tundaa'
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        x-aws-min_percent: 50
        x-aws-max_percent: 200
    secrets:
      - TUNDAA_DATABASE_PASSWORD
secrets:
  TUNDAA_DATABASE_PASSWORD:
    file: ./database_password.txt
  GITHUB_KEY:
    file: ./github_key.txt
  GITHUB_SECRET:
    file: ./github_secret.txt
  GOOGLE_KEY:
    file: ./google_key.txt
  GOOGLE_SECRET:
    file: ./google_secret.txt
