version: '3'
x-aws-vpc: "vpc-049300cf423e2a4bc"
services:
  web:
    build: .
    image: 677642048886.dkr.ecr.ap-northeast-1.amazonaws.com/tundaa:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
      - '3035:3035'
    environment:
      - 'DATABASE_PASSWORD=postgres'
      - RAILS_ENV: production
      - RAILS_SERVE_STATIC_FILES: true
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
