version: '3'
x-aws-vpc: "vpc-049300cf423e2a4bc"
services:
  web:
    build: .
    image: 677642048886.dkr.ecr.ap-northeast-1.amazonaws.com/tundaa:latest
    command: /bin/sh -c "bundle exec rails db:create db:migrate db:seed RAILS_ENV=production &&
             bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      - 'RAILS_ENV=production'
      - 'RAILS_SERVE_STATIC_FILES=true'
      - 'RAILS_LOG_TO_STDOUT=true'
      - 'RACK_ENV=production'
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - TUNDAA_DATABASE_PASSWORD=/run/secrets/database_password.txt
    secrets:
      - TUNDAA_DATABASE_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=tundaa'
      - POSTGRES_PASSWORD=/run/secrets/database_password.txt
    secrets:
      - TUNDAA_DATABASE_PASSWORD
secrets:
  TUNDAA_DATABASE_PASSWORD:
    file: ./database_password.txt
