FROM ruby:3.0
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    postgresql-client \
    yarn
  WORKDIR /tundaa
COPY Gemfile Gemfile.lock /tundaa/
RUN bundle install
COPY . .
CMD ["rails", "s", "-b", "0.0.0.0"]
