version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - '.:/tundaa'
    environment:
      - 'DATABASE_PASSWORD=postgres'
      - 'SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub'
      - 'WEBPACKER_DEV_SERVER_HOST=web'
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - '4444:4444'
      - '5901:5900'
  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
