version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up --build -d
          command: docker-compose up --build -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: setup db
          command: docker-compose exec web rails db:create db:migrate RAILS_ENV=test
      - run:
          name: rspec
          command: docker-compose exec web bin/rspec
      - run:
          name: lint
          command: docker-compose exec web bin/lint
      - run:
          name: docker-compose down
          command: docker-compose down
  test:
workflows:
  version: 2
  build:
    jobs:
      - build
